# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : The Loper House
description: Your Site Description
theme: jekyll-text-theme
lang: en

## => Author and Social
##############################
author:
  type      : person # "person" (default), "organization"
  name      : Your name
  email     :

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: user_name/repo_name
repository_tree: master

## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  rss     : # "/feed.xml" (default)

## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: false # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /node_modules
  - /screenshots

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
  - scope:
      path: "cat"
    values:
      layout: article
      nav_key: cat
      sidebar:
        nav: cat-sidebar
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_date: false


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
